import type { AiDisclosure } from "@/lib/cms/queries/articleQuery";

/** Highest degree on the reader-facing 0–N scale. */
export const AI_DISCLOSURE_MAX = 4;

export type AiDisclosureTone = "neutral" | "info" | "caution";

export interface AiDisclosureMeta {
    /** Position on the 0…AI_DISCLOSURE_MAX scale. */
    degree: number;
    /** Short human name (used in the tooltip / aria label, not shown as the badge text). */
    label: string;
    /** Full sentence for the tooltip. */
    description: string;
    tone: AiDisclosureTone;
}

export const AI_DISCLOSURE_META: Record<AiDisclosure, AiDisclosureMeta> = {
    none: {
        degree: 0,
        label: "No AI",
        description: "Written entirely by a human - no AI was used.",
        tone: "neutral",
    },
    styling: {
        degree: 1,
        label: "AI styling only",
        description: "AI was used for formatting and layout only; the writing is human.",
        tone: "neutral",
    },
    assisted: {
        degree: 2,
        label: "AI-assisted",
        description: "AI helped with research and outlining; a human wrote the article.",
        tone: "info",
    },
    redacted: {
        degree: 3,
        label: "AI-generated, human-edited",
        description: "The draft was AI-generated, then reviewed and edited by a human.",
        tone: "info",
    },
    "fully-generated": {
        degree: 4,
        label: "AI-generated",
        description: "This article was generated by AI with minimal human review.",
        tone: "caution",
    },
};

export const getAiDisclosureMeta = (value: AiDisclosure | undefined | null): AiDisclosureMeta =>
    AI_DISCLOSURE_META[value ?? "none"] ?? AI_DISCLOSURE_META.none;
