import type { AiDisclosure } from "@/lib/cms/queries/articleQuery";

export type AiDisclosureTone = "neutral" | "info" | "caution";

export interface AiDisclosureMeta {
    /** Badge label shown on the article page. */
    label: string;
    /** Longer sentence for tooltips / structured context. */
    description: string;
    tone: AiDisclosureTone;
}

export const AI_DISCLOSURE_META: Record<AiDisclosure, AiDisclosureMeta> = {
    none: {
        label: "Written by a human",
        description: "No AI was used to write this article.",
        tone: "neutral",
    },
    styling: {
        label: "AI: formatting only",
        description: "AI was used for formatting and layout only; the writing is human.",
        tone: "neutral",
    },
    assisted: {
        label: "AI-assisted",
        description: "AI helped with research and outlining; a human wrote the article.",
        tone: "info",
    },
    redacted: {
        label: "AI-generated, human-edited",
        description: "The draft was AI-generated, then reviewed and edited by a human.",
        tone: "info",
    },
    "fully-generated": {
        label: "AI-generated",
        description: "This article was generated by AI with minimal human review.",
        tone: "caution",
    },
};

export const getAiDisclosureMeta = (value: AiDisclosure | undefined): AiDisclosureMeta =>
    AI_DISCLOSURE_META[value ?? "none"] ?? AI_DISCLOSURE_META.none;
