[[plugins]]
  package = "netlify-plugin-discord"

[[redirects]]
  from = "https://arpg-timeline.netlify.app/*"
  to = "https://arpg-timeline.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://arpg-timeline.ayronk.com/*"
  to = "https://arpg-timeline.com/:splat"
  status = 301
  force = true