local_backend: true

backend:
  name: git-gateway
  repo: AyronK/arpg-timeline
  branch: decap
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img

collections:
  - label: "Crawler | HTTP"
    name: "crawlerSources_http"
    label_singular: "Crawler HTTP source"
    editor:
      preview: false
    folder: "src/documents/crawlerSources"
    summary: "HTTP source | {{game}} | {{source}}"
    filter:
      - field: "type"
        value: "http"
    create: true
    view_groups:
      - label: Game
        field: game
    fields:
      - label: "Type"
        name: "type"
        widget: "hidden"
        default: "http"

      - label: "Game"
        name: "game"
        widget: "relation"
        collection: "games"
        search_fields: ["name", "slug", "shortName"]
        value_field: "name"
        display_fields: ["name"]

      - label: "Crawler keywords"
        name: "keywords"
        widget: "list"
        allow_add: true
        max: 10

      - label: "Source URL"
        name: "source"
        widget: "string"
        allow_add: true
        required: true
        max: 3

  - label: "Crawler | Steam"
    name: "crawlerSources_steam"
    label_singular: "Crawler Steam source"
    editor:
      preview: false
    folder: "src/documents/crawlerSources"
    create: true
    summary: "Steam source | {{game}}"
    view_groups:
      - label: Game
        field: game
    filter:
      - field: "type"
        value: "steam"
    fields:
      - label: "Type"
        name: "type"
        widget: "hidden"
        default: "steam"

      - label: "Game"
        name: "game"
        widget: "relation"
        collection: "games"
        search_fields: ["name", "shortName"]
        value_field: "name"
        display_fields: ["name"]

      - label: "Crawler keywords"
        name: "keywords"
        widget: "list"
        allow_add: true
        max: 10

      - label: "Steam ID"
        name: "steamId"
        widget: "string"
        required: true

      - label: "Crawl RSS Descriptions"
        name: "crawlDescriptions"
        widget: "boolean"
        required: false
        default: false

      - label: "Notify about new RSS messages"
        name: "notifyAboutNews"
        widget: "boolean"
        required: false
        default: false

  - label: "Crawler | Reddit"
    name: "crawlerSources_reddit"
    label_singular: "Crawler Reddit source"
    editor:
      preview: false
    folder: "src/documents/crawlerSources"
    create: true
    summary: "Reddit source | {{game}}"
    view_groups:
      - label: Game
        field: game
    filter:
      - field: "type"
        value: "reddit"
    fields:
      - label: "Type"
        name: "type"
        widget: "hidden"
        default: "reddit"

      - label: "Game"
        name: "game"
        widget: "relation"
        collection: "games"
        search_fields: ["name", "shortName"]
        value_field: "name"
        display_fields: ["name"]

      - label: "Crawler keywords"
        name: "keywords"
        widget: "list"
        allow_add: true
        max: 10

      - label: "Subreddit"
        name: "steamId"
        widget: "string"
        required: true

  - label: "Games"
    name: "games"
    summary: "{{name}}"
    label_singular: "Game"
    editor:
      preview: false
    folder: "src/pages/games"
    create: true
    slug: "{{fields.name}}"
    fields:
      - label: "Name"
        name: "name"
        widget: "string"
        required: true

      - label: "Short name"
        name: "shortName"
        widget: "string"
        required: false

      - label: "Season keyword"
        name: "seasonKeyword"
        widget: "string"
        required: true

      - label: "Is this an official game/ladder?"
        name: "official"
        widget: "boolean"
        required: true
        default: true

      - label: "Group"
        name: "group"
        widget: "string"
        required: false

      - label: "Logo"
        name: "logo"
        widget: "image"
        required: true
        media_library:
          config:
            max_file_size: 512000

      - label: "Url"
        name: "url"
        widget: "string"
        required: false

  - label: "Seasons"
    name: "seasons"
    sortable_fields: ["name", "start.startDate"]
    label_singular: "Season"
    editor:
      preview: false
    folder: "src/documents/seasons"
    create: true
    slug: "{{fields.game}}-{{fields.name}}"
    summary: "{{game}} | {{name}}"
    view_groups:
      - label: Game
        field: game
    fields:
      - label: "Game"
        name: "game"
        widget: "relation"
        collection: "games"
        search_fields: ["name", "slug", "shortName"]
        value_field: "name"
        display_fields: ["name"]

      - label: "Name"
        name: "name"
        widget: "string"
        required: true

      - label: "Url"
        name: "url"
        widget: "string"
        required: false

      - label: "Start"
        name: "start"
        widget: "object"
        required: false
        collapsed: false
        fields:
          - label: "Start Date UTC"
            name: "startDate"
            widget: "datetime"
            picker_utc: true
            required: false

          - label: "Confirmed"
            name: "confirmed"
            widget: "boolean"
            required: false
            default: false

          - label: "Override text"
            name: "overrideText"
            widget: "string"
            required: false

          - label: "Additional text"
            name: "additionalText"
            widget: "string"
            required: false

      - label: "End"
        name: "end"
        widget: "object"
        required: false
        collapsed: false
        fields:
          - label: "End Date UTC"
            name: "endDate"
            default: ""
            widget: "datetime"
            picker_utc: true
            required: false

          - label: "Confirmed"
            name: "confirmed"
            widget: "boolean"
            required: false
            default: false

          - label: "Override text"
            name: "overrideText"
            widget: "string"
            required: false

          - label: "Additional text"
            name: "additionalText"
            widget: "string"
            required: false
