backend:
  name: github
  repo: AyronK/arpg-timeline
  branch: main
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"
media_folder: static/img
public_folder: /img

collections:
  - label: "Games"
    name: "games"
    label_singular: "Game"
    editor:
      preview: false
    folder: "src/pages/games"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

      - label: "Season keyword"
        name: "seasonKeyword"
        widget: "string"
        required: true

      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Short name"
        name: "shortName"
        widget: "string"
        required: false

      - label: "Logo"
        name: "logo"
        widget: "image"
        required: true
        media_library:
          config:
            max_file_size: 512000

      - label: "Url"
        name: "url"
        widget: "string"
        required: false

      - label: "Current season"
        name: "currentSeason"
        widget: "object"
        required: false
        collapsed: true
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false

          - label: "Url"
            name: "url"
            widget: "string"
            required: false

          - label: "Start date (UTC)"
            name: "startDate"
            default: ""
            widget: "datetime"
            picker_utc: true
            required: true

          - label: "Start date notice"
            name: "startDateNotice"
            widget: "string"
            required: false

          - label: "End date (UTC)"
            name: "endDate"
            default: ""
            widget: "datetime"
            picker_utc: true
            required: true

          - label: "End date notice"
            name: "endDateNotice"
            widget: "string"
            required: false

      - label: "Next season"
        name: "nextSeason"
        widget: "object"
        collapsed: true
        required: false
        fields:
          - label: "Title"
            name: "title"
            widget: "string"
            required: false

          - label: "Url"
            name: "url"
            widget: "string"
            required: false

          - label: "Start date (UTC)"
            name: "startDate"
            default: ""
            widget: "datetime"
            picker_utc: true
            required: true

          - label: "Start date notice"
            name: "startDateNotice"
            widget: "string"
            required: false

          - label: "Show countdown"
            name: "showCountdown"
            widget: "boolean"
            required: false

  - label: "RSS Messages"
    label_singular: "RSS Message"
    name: "rss_messages"
    folder: "src/pages/rss"
    create: true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Date"
        name: "date"
        widget: "datetime"
        picker_utc: true

      - label: "Author"
        name: "author"
        widget: "string"

      - label: "Link"
        name: "link"
        widget: "string"
        required: false

      - label: "Content"
        name: "content"
        widget: "markdown"
        required: false

      - label: "Image"
        name: "image"
        widget: "image"
        required: false
        media_library:
          config:
            max_file_size: 512000

      - label: "Image Link"
        name: "imageLink"
        widget: "string"
        required: false
