backend:
  name: github
  repo: AyronK/arpg-timeline
media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "game" # Used in routes, e.g., /admin/collections/blog
    label: "Game" # Used in the UI
    folder: "games" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }