backend:
  name: github
  repo: AyronK/arpg-timeline
media_folder: static/img
public_folder: /img

collections:
  - name: "games"
    label: "Games"
    label_singular: 'Game'
    editor:
     preview: false
    folder: "content/games" 
    create: true
    slug: "{{fields.slug}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
        required: true

      - label: "Order"
        name: "order"
        widget: "number"
        required: true

      - label: "Season keyword"
        name: "seasonKeyword"
        widget: "string"
        required: true

      - label: "Title"
        name: "title"
        widget: "string"
        required: true

      - label: "Logo"
        name: "logo"
        widget: "image"
        required: true
        media_library:
          config:
            max_file_size: 512000

      - label: "Current season"
        name: "currentSeason"
        widget: "object"
        required: false
        collapsed: true
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"            
            required: false

          - label: "Url"
            name: "url"
            widget: "string"
            required: false

          - label: "Start date (UTC)"
            name: "startDate"
            default: ""
            widget: "datetime"
            picker_utc: true
            required: false

          - label: "Start date notice"
            name: "startDateNotice"
            widget: "string"
            required: false

          - label: "End date (UTC)"
            name: "endDate"
            default: ""
            widget: "datetime"
            picker_utc: true
            required: false

          - label: "End date notice"
            name: "endDateNotice"
            widget: "string"
            required: false

      - label: "Next season"
        name: "nextSeason"
        widget: "object"
        collapsed: true
        required: false
        fields: 
          - label: "Title"
            name: "title"
            widget: "string"
            required: false

          - label: "Url"
            name: "url"
            widget: "string"
            required: false

          - label: "Start date (UTC)"
            name: "startDate"
            default: ""
            widget: "datetime"
            picker_utc: true
            required: false

          - label: "Start date notice"
            name: "startDateNotice"
            widget: "string"
            required: false

          - label: "Show countdown"
            name: "showCountdown"
            widget: "boolean"
            required: false
