name: Crawl sources and notify Discord

on:
  workflow_dispatch:    

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./scripts/crawler
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: Set up Node.js
      uses: actions/setup-node@v4.0.3

    - name: Install dependencies
      run: npm install

    - name: Run script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: npm run crawl
